### ISSUE TITLE
pystatgrab not getting compiled

### ISSUE THREAD

**Issue by shaheena86** [libstatgrab/pystatgrab#8]
Hi,

I am using 
Python 3.11
Debian 12
pystatgrab 0.7.1
libstatgrab 0.91

I am using the below command :
python3 setup.py build bdist --format=tar
statgrab.c:196:12: fatal error: longintrepr.h: No such file or directory
  196 |   #include "longintrepr.h"
      |            ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

could you guys help me here ?

**Comment by tdb** [comment]
Hi,

Do you have the python3-dev package installed?

Tim.

**Comment by shaheena86** [comment]
Yes.
I am installing these before the above command,
apt-get install -y pkg-config libtool libtool-bin
apt-get install -y python3.11-dev
apt-get install libpython3.11-dev -y
apt-get install wget curl git -y
apt-get install python3-dev -y

**Comment by tdb** [comment]
I've just done the following on a Debian 12 docker image as a test:

```
apt-get update
apt-get install -y python3-dev libstatgrab-dev git python-is-python3 pkg-config build-essential cython3
git clone https://github.com/libstatgrab/pystatgrab.git
cd pystatgrab
./setup.py build
```

If I download `pystatgrab-0.7.1.tar.gz` and try to build that I see the same error.

Comparing the generated `statgrab.c` I see:

```diff
-  #include "longintrepr.h"
+  #if PY_MAJOR_VERSION < 3
+    #include "longintrepr.h"
+  #endif
```

Looks like we made need to repackage it with a newer Cython version.

**Comment by tdb** [comment]
No ETA. Given it's trivially easy to build from git, or [create your own tarball](https://github.com/libstatgrab/pystatgrab/blob/master/.gitlab-ci.yml#L22), it shouldn't be a blocker.

**Comment by shaheena86** [comment]
cool, thanks for the help :)
